Social_Nerwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('landing.urls'), name='accounts'),
    path('', include('my_profile.urls')),
    path('chat/', include('chat.urls',)),
    path('oauth/', include('social_django.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path, re_path

from chat import views

urlpatterns = [
    # path('', views.index, name='chat'),
    re_path(r'^(?P<room_name>[^/]+)/$', views.room, name='room'),
]

landing/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import (
	LoginView, LogoutView,
)

from my_profile.views import ViewProfile
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='accounts:login'),
         name='logout'),
    # re_path(r'^profile/(?P<id>\d+)/', ViewProfile.as_view(), name='profile'),

    # re_path(r'^profile/(?P<id>\d+)/$', views.view_profile,
    #         name='view_profile_with_pk'),
    # path('profile/', views.view_profile, name='view_profile'),
    re_path(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$', views.change_friends,
            name='change_friends'),
    path('friends/', views.view_friends, name='view_friends'),
    # re_path(r'^view_profile_friend/(?P<pk>\d+)/$', views.view_profile_friend, name='view_profile_friend'),
]

templates/accounts/add_profile_image.html
<{% extends 'base.html' %}
{% load static %}

{% block content %}
    <form action="{% url 'add_profile_image_url'%}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
                {{ field.label }}
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-dark">Create post</button>
    </form>
{% endblock %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <form action="{% url 'edit_profile' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
                {{ field.label }}
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Create post</button>
    </form>
{% endblock %}


     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

templates/accounts/friends.html
{% extends 'profile_base2.html' %}
{% load static %}


{% block profile2 %}
    <div class="container main-secction">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12 image-section">
                    <img src="/static/media/profile_image/cap.jpg">
                </div>
                <div class="row user-left-part">
                    <div class="col-md-3 col-sm-3 col-xs-12 pull-left">
                        <div class="row ">
                            {% if user.userprofile.image %}
                                <div class="col-md-12 col-md-12-sm-12 col-xs-12 user-image text-center">
                                    <img src="{{ user.userprofile.image.url}}" class="rounded-circle">
                                </div>
                            {% else %}
                                <div class="col-md-12 col-md-12-sm-12 col-xs-12 user-image text-center">
                                    <img src="{% static 'media/profile_image/anonnymous.jpg' %}" class="rounded-circle">
                                </div>
                            {% endif %}

                            <div class="row user-detail-row">
                                <div class="col-md-12 user-detail-section2 pull-left">
                                    <div class="border"></div>
                                    <p>FOLLOWER</p>
                                     <div class="followers">
                                            {{ followers }}
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="col-md-9 col-sm-9 col-xs-12 pull-right profile-right-section" style="background-color: #c0c0c0">
                        <div class="row profile-right-section-row">
                            <div class="col-md-12 profile-header">
                                <div class="row">
                                    <div class="col-md-8 col-sm-6 col-xs-6 profile-header-section1 pull-left">
                                        <h1>{{ user.first_name }} {{ user.last_name }}</h1>
                                        <h5>Developer</h5>
                                    </div>
                                    {% if user in friends %}
                                        <div class="remove-add-friend">
                                            <a href="{% url 'accounts:change_friends' operation='remove' pk=user.pk %}" class ="btn btn-dark">Remove friend</a>
                                        </div>
                                    {% else %}
                                        <div class="remove-add-friend">
                                            <a href="{% url 'accounts:change_friends' operation='add' pk=user.pk %}" class ="btn btn-dark">Add friend</a>
                                        </div>
                                    {% endif %}
                                    <div class="message">
                                        <a href="{{ room }}" class="btn btn-dark">Send message</a>
                                    </div>

                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-8">
                                            <ul class="nav nav-tabs" role="tablist">
                                                    <li class="nav-item">
                                                      <a class="nav-link" id="profile" onclick="checked()"> Profile information</a>
                                                    </li>
                                                    <li class="nav-item">
                                                      <a class="nav-link" id="friends" onclick="checked_second()"> Friends</a>
                                                    </li>
                                                    <li class="nav-item">
                                                      <a class="nav-link" id="other-users" onclick="checked_third()"> Other people</a>
                                                    </li>
                                                  </ul>

                                                  <!-- Tab panes -->
                                                  <div class="tab-content" id="view">
                                                    <div role="tabpanel" class="tab-pane fade show active" >
                                                            <div class="row">
                                                                <div class="col-md-2">
                                                                    <label>Id: </label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>{{ user.id }}</p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-2">
                                                                    <label>Email: </label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>{{ user.email }}</p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-2">
                                                                    <label>Description: </label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>{{ user.userprofile.description }}</p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-2">
                                                                    <label>City: </label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>{{ user.userprofile.city }}</p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-2">
                                                                    <label>Website: </label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>{{ user.userprofile.website }}</p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-2">
                                                                    <label>Phone: </label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>{{ user.userprofile.phone }}</p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-2">
                                                                    <label>Sex: </label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>{{ user.userprofile.sex }}</p>
                                                                </div>
                                                            </div>
                                                    </div>
                                    </div>
                                    <div class="users" id="users">
                                            {% for client in users %}
                                                {% if client in friends %}
                                                    {% if client.first_name and client.last_name %}
                                                        <a href="{% url 'accounts:view_profile_friend' pk=client.pk %}">
                                                            <div class="blog-post">
                                                                <p>{{ client.first_name }} {{ client.last_name }}</p>
                                                            </div>
                                                        </a>
                                                    {% else %}
                                                        <p>Anonymous user</p>
                                                    {% endif %}
                                                {% endif %}
                                            {% endfor %}

                                    </div>
                                    <div class="other" id="other">
                                        {% for client in users %}
                                            {% if not client in friends %}
                                                {% if client.first_name and client.last_name %}
                                                    <a href="{% url 'accounts:view_profile_friend' pk=client.pk %}">
                                                        <div class="blog-post">
                                                            <p>{{ client.first_name }} {{ client.last_name }}</p>
                                                        </div>
                                                    </a>
                                                {% endif %}
                                            {% endif %}

                                                {% if not client.first_name and client.last_name %}
                                                    <div class="but-friend">
                                                        <a href="{% url 'accounts:change_friends' operation='add' pk=client.pk %}" class ="btn btn-add-friend">Add friend</a>
                                                    </div>
                                                    <p>Anonymous user</p>
                                                {% endif %}
                                        {% endfor %}
                                    </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 fixed">
                <h3 class="pb-4 mb-4 font-italic border-bottom">
                    My posts
                </h3>
                    {% for field in post %}
                          <div class="blog-post">
                            <h2 class="blog-post-title">{{ field.title }}</h2>
                            <p class="blog-post-meta">{{ field.created }}</p>
                            <p>{{ field.content }}</p>
                          </div><!-- /.blog-post -->
                    {% endfor %}

                </div>

            </div>

        </div>

{% endblock %}

templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V4</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/iconic/css/material-design-iconic-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100" style="background: silver">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
				<form method="post" class="login100-form validate-form">
                    {% csrf_token %}
					<span class="login100-form-title p-b-49">
						Login
					</span>
					<div class="wrap-input100 validate-input m-b-23" data-validate = "Username is reauired">
						<span class="label-input100">Username</span>
						    {{ form.username}}
					</div>

					<div class="wrap-input100 validate-input m-b-23" data-validate="Password is required">
						<span class="label-input100">Password</span>
                            {{ form.password }}
					</div>

					<div class="text-right p-t-8 p-b-31">
						<a href="#">
							Forgot password?
						</a>
					</div>

					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								Login
							</button>
						</div>
					</div>

					<div class="flex-col-c p-t-155">
						<span class="txt1 p-b-17">
							Or Sign Up Using
						</span>

						<a href="#" class="txt2">
							Sign Up
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/daterangepicker/moment.min.js"></script>
	<script src="vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="js/main.js"></script>

</body>
</html>

templates/accounts/profile_information.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400" rel="stylesheet">

    <link rel = "stylesheet" href="{% static '/css/my_profile.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>Page</title>
  </head>

  </head>
  <body>
  {% block content %}
    <div class="container">
      <div class="edit-profile">
        <h1>{{ user.first_name }} {{ user.last_name }}</h1>
          <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    {% if user.userprofile.image %}
                        <img src="{{ user.userprofile.image.url }}" class="img-fluid">
                    {% endif %}
                </div>
            </div>
          </div>
        <p class="lead">Email: {{ user.email }}</p>
        <p class="lead">Description: {{ user.userprofile.description }}</p>
        <p class="lead">City: {{ user.userprofile.city }}</p>
        <p class="lead">Website: {{ user.userprofile.website }}</p>
        <p class="lead">Phone: {{ user.userprofile.phone }}</p>
        <p class="lead">Sex: {{ user.userprofile.sex }}</p>
        <a class="btn btn-lg btn-primary" href="{% url 'accounts:view_profile' %} " role="button">Back</a>
      </div>
    </div>
  {% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

templates/accounts/reg_form.html
{#{% extends 'base.html' %}#}
{##}
{##}
{#{% block content %}#}
{#    <div class="container">#}
{#		<h1>Register</h1>#}
{#		<form method="post">#}
{#			{% csrf_token %}#}
{#			{{ form.as_p }}#}
{#			<button type="submit">Submit</button>#}
{#		</form>#}
{#	</div>#}
{#{% endblock %}#}

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V4</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/iconic/css/material-design-iconic-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100" style="background: silver">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
				<form class="login100-form validate-form" method="post" action="{% url "accounts:register" %}">
                    {% csrf_token %}
					<span class="login100-form-title p-b-49">
						Register
					</span>

					<div class="wrap-input100 validate-input m-b-23" data-validate = "Username is reauired">
						<span class="label-input100">Username</span>
						    {{ form.username }}
					</div>
                    <div class="wrap-input100 validate-input m-b-23" data-validate = "Username is reauired">
						<span class="label-input100">First name</span>
						    {{ form.first_name }}
					</div>
                    <div class="wrap-input100 validate-input m-b-23" data-validate = "Username is reauired">
						<span class="label-input100">Last name</span>
						    {{ form.last_name }}
					</div>
                    <div class="wrap-input100 validate-input m-b-23" data-validate = "Username is reauired">
						<span class="label-input100">Email</span>
						    {{ form.email }}
					</div>

					<div class="wrap-input100 validate-input m-b-23" data-validate="Password is required">
						<span class="label-input100">Password</span>
                            {{ form.password1 }}
					</div>
                    <div class="wrap-input100 validate-input m-b-23" data-validate="Password is required">
						<span class="label-input100">Repeat password</span>
                            {{ form.password2 }}
					</div>

					<div class="text-right p-t-8 p-b-31">
						<a href="#">
							Forgot password?
						</a>
					</div>

					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								Register
							</button>
						</div>
					</div>
					<div class="flex-col-c p-t-155">
						<span class="txt1 p-b-17">
							Or Sign Up Using
						</span>

						<a href="#" class="txt2">
							Sign Up
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/daterangepicker/moment.min.js"></script>
	<script src="vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="js/main.js"></script>

</body>
</html>

templates/accounts/update_edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <form action="{% url 'edit_profile_url'  pk=user.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
                {{ field.label }}
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-dark">Edit</button>
    </form>
{% endblock %}