Social_Nerwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('landing.urls'), name='accounts'),
    path('', include('my_profile.urls')),
    path('chat/', include('chat.urls',)),
    path('oauth/', include('social_django.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path, re_path

from chat import views

urlpatterns = [
    # path('', views.index, name='chat'),
    re_path(r'^(?P<room_name>[^/]+)/$', views.room, name='room'),
]

landing/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import (
	LoginView, LogoutView,
)

from my_profile.views import ViewProfile
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='accounts:login'),
         name='logout'),
    # re_path(r'^profile/(?P<id>\d+)/', ViewProfile.as_view(), name='profile'),

    # re_path(r'^profile/(?P<id>\d+)/$', views.view_profile,
    #         name='view_profile_with_pk'),
    # path('profile/', views.view_profile, name='view_profile'),
    re_path(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$', views.change_friends,
            name='change_friends'),
    path('friends/', views.view_friends, name='view_friends'),
    # re_path(r'^view_profile_friend/(?P<pk>\d+)/$', views.view_profile_friend, name='view_profile_friend'),
]

templates/include/navbar.html
<div class="navbar">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="{% url 'posts_list_url' %}">Posts</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">


            {% if request.user.is_authenticated %}
{#                  <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'profile_information_url' %}">Profile information</a>#}
{#                  </li>#}
                  </li>
                  <li class="nav-item">
{#                    <a class="nav-link" href="{% url 'profile' id=user.id %}">My profile</a>#}
                  </li>
                  <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                  </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                  </li>
            {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                  </li>
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                  </li>
            {% endif %}
        </ul>

      </div>
    </nav>
</div>

templates/include/post_card.html
<div class="card">
            <div class="card-header">
                {{ post.create }}
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ post.title }}</h5>
                <p class="card-text">{{ post.content|truncatewords:100}}</p>
                <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Read</a>
            </div>
        </div>